/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view.employee;

import com.mycompany.Object.PhieuMuon.PhieuMuon;
import com.mycompany.Object.PhieuMuon.PhieuMuonBUS;
import java.util.ArrayList;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.DataFormat;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import com.mycompany.Object.PhieuTra.PhieuTra;
import com.mycompany.Object.PhieuTra.PhieuTraBUS;
import com.mycompany.Object.Sach.Sach;
import com.mycompany.Object.Sach.SachBUS;
import com.mycompany.Object.USER.User;
import com.mycompany.Object.USER.UserBUS;
import com.mycompany.controller.TaiKhoanController;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.time.LocalDate;

/**
 *
 * @author khang
 */
public class PhieuTraJPanel extends javax.swing.JPanel {

        PhieuTraBUS phieuTraBUS = new PhieuTraBUS();
        DefaultTableModel model;
        ArrayList<PhieuTra> list = new ArrayList<PhieuTra>();

        PhieuMuonBUS phieuMuonBus = new PhieuMuonBUS();
        ArrayList<PhieuMuon> listPhieuMuon = new ArrayList<PhieuMuon>();

        UserBUS userBUS = new UserBUS();
        ArrayList<User> listusers = new ArrayList<User>();

        ArrayList<Sach> arr = new ArrayList<Sach>();
        SachBUS sachBUS = new SachBUS();

        /**
         * Creates new form PhieuTraJPanel
         */
        public PhieuTraJPanel() {
                initComponents();
                LoadData();
        }

        public void LoadData() {

                model = (DefaultTableModel) jTablePhieuTra.getModel();
                model.setRowCount(0);
                list = phieuTraBUS.getDSPhieuTra();
                int i = 0;
                while (i <= list.size() - 1) {
                        PhieuTra nv = list.get(i);
                                model.addRow(new Object[] {
                                                ++i, nv.getMaPhieu(), nv.getMaPhieuMuon(), nv.getMaDocGia(),
                                                nv.getMaSach(), nv.getMaNhanVien(),
                                                Menu.MenuHand.convert(nv.getHanTra()),
                                                Menu.MenuHand.convert(nv.getNgayTra()), nv.getSoLuong(),
                                                nv.getTinhTrang(), nv.getSoNgayQuaHan()
                                });
                                jTablePhieuTra.setModel(model);
                        

                }

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfMaPhieu = new javax.swing.JTextField();
        tfMaPhieuMuon = new javax.swing.JTextField();
        tfMaDG = new javax.swing.JTextField();
        tfMaSach = new javax.swing.JTextField();
        tfMaNhanVien = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tfSoLuong = new javax.swing.JTextField();
        tfHanTra = new javax.swing.JTextField();
        tfNgayTra = new javax.swing.JTextField();
        tfTinhTrang = new javax.swing.JTextField();
        tfSoNgayQuaHan = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnInExcel = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePhieuTra = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Phiếu trả"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridLayout(5, 0, 0, 10));

        jLabel1.setText("MAPHIEU");
        jPanel2.add(jLabel1);

        jLabel3.setText("Mã phiếu mượn");
        jPanel2.add(jLabel3);

        jLabel2.setText("Mã đọc giả");
        jPanel2.add(jLabel2);

        jLabel10.setText("Mã sách");
        jPanel2.add(jLabel10);

        jLabel4.setText("Mã nhân viên");
        jPanel2.add(jLabel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 10, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridLayout(5, 0, 0, 10));

        tfMaPhieu.setEditable(false);
        jPanel3.add(tfMaPhieu);
        jPanel3.add(tfMaPhieuMuon);

        tfMaDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaDGActionPerformed(evt);
            }
        });
        jPanel3.add(tfMaDG);
        jPanel3.add(tfMaSach);

        tfMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaNhanVienActionPerformed(evt);
            }
        });
        jPanel3.add(tfMaNhanVien);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 6, 0, 0);
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridLayout(5, 0, 0, 10));

        jLabel5.setText("Hạn trả");
        jPanel4.add(jLabel5);

        jLabel6.setText("Ngày trả");
        jPanel4.add(jLabel6);

        jLabel7.setText("Số lượng");
        jPanel4.add(jLabel7);

        jLabel8.setText("Tình trạng");
        jPanel4.add(jLabel8);

        jLabel9.setText("Số ngày quá hạn");
        jPanel4.add(jLabel9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 6, 0, 0);
        jPanel1.add(jPanel4, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridLayout(5, 0, 0, 10));
        jPanel5.add(tfSoLuong);

        tfHanTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHanTraActionPerformed(evt);
            }
        });
        jPanel5.add(tfHanTra);
        jPanel5.add(tfNgayTra);

        tfTinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTinhTrangActionPerformed(evt);
            }
        });
        jPanel5.add(tfTinhTrang);
        jPanel5.add(tfSoNgayQuaHan);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 6, 0, 5);
        jPanel1.add(jPanel5, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel6.add(btnThem);

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Delete.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel6.add(btnXoa);

        btnInExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Export Excel.png"))); // NOI18N
        btnInExcel.setText("In Excel");
        btnInExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInExcelActionPerformed(evt);
            }
        });
        jPanel6.add(btnInExcel);

        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/Refresh.png"))); // NOI18N
        btnLoad.setText("Load thông tin");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        jPanel6.add(btnLoad);

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icons/cleaning.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel6.add(btnClear);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 24, 5, 0);
        jPanel1.add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 6, 0, 6);
        add(jPanel1, gridBagConstraints);

        jTablePhieuTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phiếu", "Mã phiếu mượn", "MADG", "Mã sách", "MANV", "Hạn trả", "Ngày trả", "Số lượng", "Tình trạng", "Số ngày quá hạn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePhieuTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePhieuTraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePhieuTra);
        if (jTablePhieuTra.getColumnModel().getColumnCount() > 0) {
            jTablePhieuTra.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 619;
        gridBagConstraints.ipady = 207;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 6, 6);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInExcelActionPerformed
        // TODO add your handling code here:
        try{
                JFileChooser fChooser = new JFileChooser();
                int choose = fChooser.showSaveDialog(null);
                if(choose == JFileChooser.APPROVE_OPTION) {
                    XSSFWorkbook workbook = new XSSFWorkbook();
                    XSSFSheet sheet = workbook.createSheet("Phiếu trả");
                    XSSFRow row = null;
                    Cell cell = null;
                    row = sheet.createRow(3);
    
                    String dateFormat = "yyyy-MM-dd";
                    CellStyle style = workbook.createCellStyle();
                    DataFormat dataFormat = workbook.createDataFormat();
                    style.setDataFormat(dataFormat.getFormat(dateFormat));
    
                    cell = row.createCell(0, CellType.STRING);
                    cell.setCellValue("STT");
    
                    cell = row.createCell(1, CellType.STRING);
                    cell.setCellValue("Mã phiếu");
    
                    cell = row.createCell(2, CellType.STRING);
                    cell.setCellValue("Mã phiếu mượn");
    
                    cell = row.createCell(3, CellType.STRING);
                    cell.setCellValue("Mã độc giả");
    
                    cell = row.createCell(4, CellType.STRING);
                    cell.setCellValue("Mã sách");
    
                    cell = row.createCell(5, CellType.STRING);
                    cell.setCellValue("Mã nhân viên");
    
                    cell = row.createCell(6, CellType.STRING);
                    cell.setCellValue("Hạn trả");
    
                    cell = row.createCell(7, CellType.STRING);
                    cell.setCellValue("Ngày trả");
    
                    cell = row.createCell(8, CellType.STRING);
                    cell.setCellValue("Số lượng");

                    cell = row.createCell(9, CellType.STRING);
                    cell.setCellValue("Tình trạng");

                    cell = row.createCell(10, CellType.STRING);
                    cell.setCellValue("Số ngày quá hạn");
    
                    ArrayList<PhieuTra> arr = phieuTraBUS.getDSPhieuTra();
    
                    for(int i = 0; i < arr.size(); i++) {
                        row = sheet.createRow(4 + i);
    
                        cell = row.createCell(0, CellType.NUMERIC);
                        cell.setCellValue(i + 1);
    
                        cell = row.createCell(1, CellType.STRING);
                        cell.setCellValue(arr.get(i).getMaPhieu());
    
                        cell = row.createCell(2, CellType.STRING);
                        cell.setCellValue(arr.get(i).getMaPhieuMuon());
    
                        cell = row.createCell(3, CellType.STRING);
                        cell.setCellValue(arr.get(i).getMaDocGia());
    
                        cell = row.createCell(4, CellType.STRING);
                        cell.setCellValue(arr.get(i).getMaSach());
    
                        cell = row.createCell(5, CellType.STRING);
                        cell.setCellValue(arr.get(i).getMaNhanVien());

                        cell = row.createCell(6);
                        cell.setCellValue(arr.get(i).getHanTra());
                        cell.setCellStyle(style);    
                        
                        cell = row.createCell(7);
                        cell.setCellValue(arr.get(i).getNgayTra());
                        cell.setCellStyle(style);    
    
                        cell = row.createCell(8, CellType.NUMERIC);
                        cell.setCellValue(arr.get(i).getSoLuong());

                        cell = row.createCell(9, CellType.STRING);
                        cell.setCellValue(arr.get(i).getTinhTrang());
    
                        cell = row.createCell(10, CellType.NUMERIC);
                        cell.setCellValue(arr.get(i).getSoNgayQuaHan());
                    }
    
                    File file = new File(fChooser.getSelectedFile().toString() + ".xlsx");
                    try {
                        FileOutputStream fo = new FileOutputStream(file);
                        workbook.write(fo);
                        JOptionPane.showMessageDialog(this, "Đã in!");
                        fo.close();
                        workbook.close();
                    } catch(FileNotFoundException e) {
                        System.out.println(e);
                    }
                }
                
            } catch(Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_btnInExcelActionPerformed

        private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemActionPerformed
                // TODO add your handling code here:
                // Mã phiếu tạo tự động, lấy mã phiếu mượn của phiếu mượn cuối cùng đưa vào
                // tfMaPhieu.setText(Menu.MenuHand.FormatString(Mượn)

                try {
                        if (tfMaPhieuMuon.getText().equals("") || tfMaDG.getText().equals("")
                                        || tfMaNhanVien.getText().equals("") || tfNgayTra.getText().equals("")
                                        || tfHanTra.getText().equals("") || tfSoLuong.getText().equals("")
                                        || tfTinhTrang.getText().equals("")) {
                                JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
                        } else {
                                PhieuTra phieuTra = new PhieuTra();
                                phieuTra.setMaPhieu(tfMaPhieu.getText());
                                phieuTra.setMaPhieuMuon(tfMaPhieuMuon.getText());
                                phieuTra.setMaDocGia(tfMaDG.getText());
                                phieuTra.setMaNhanVien(tfMaNhanVien.getText());
                                phieuTra.setMaSach(tfMaSach.getText());
                                phieuTra.setHanTra(Menu.MenuHand.convert(tfHanTra.getText()));
                                phieuTra.setNgayTra(Menu.MenuHand.convert(tfNgayTra.getText()));
                                phieuTra.setSoLuong(Integer.parseInt(tfSoLuong.getText()));
                                phieuTra.setTinhTrang(tfTinhTrang.getText());
                                phieuTra.setSoNgayQuaHan(Integer.parseInt(tfSoNgayQuaHan.getText()));
                                if (phieuTraBUS.addPhieuTra(phieuTra).equals("Thêm thành công")) {
                                        try {
                                                ArrayList<Sach> arr = new ArrayList<Sach>();
                                                arr = sachBUS.loadData();
                                                SachBUS sachBUS = new SachBUS();
                                                for (Sach sach : arr) {
                                                        if (sach.getMaSach().equals(tfMaSach.getText())) {
                                                                Sach sa = new Sach();
                                                                sa.setMaSach(sach.getMaSach());
                                                                sa.setSoLuong(sach.getSoLuong());
                                                                sa.setSoLuongSau(Integer.parseInt(tfSoLuong.getText()));
                                                                JOptionPane.showMessageDialog(this,
                                                                                sachBUS.TraSach(sa));
                                                                break;
                                                        }
                                                }
                                        } catch (Exception e) {
                                        }
                                }

                                jTablePhieuTra.repaint();
                                refreshData();
                        }

                } catch (Exception ex) {

                }

        }// GEN-LAST:event_btnThemActionPerformed

        public void refreshData() {
                phieuTraBUS = new PhieuTraBUS();
                LoadData();
        }

        private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaActionPerformed
                // TODO add your handling code here:
                ArrayList<PhieuTra> arr = new ArrayList<PhieuTra>();
                arr = phieuTraBUS.getDSPhieuTra();
                int reply = JOptionPane.showConfirmDialog(getRootPane(),
                                "Bạn có chắc muốn xoá " + tfMaPhieu.getText() + " không ?", "Chú ý",
                                JOptionPane.YES_NO_OPTION);

                if (reply == JOptionPane.YES_OPTION) {
                        for (PhieuTra nxb : arr) {
                                if (nxb.getMaPhieu().equals(tfMaPhieu.getText().trim())) {
                                        phieuTraBUS.deleted(nxb);
                                        break;
                                }
                        }
                }
                model.setRowCount(0);
                refreshData();
        }// GEN-LAST:event_btnXoaActionPerformed

        private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuaActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnSuaActionPerformed

        private void jTablePhieuTraMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTablePhieuTraMouseClicked
                // TODO add your handling code here:
                int i = jTablePhieuTra.getSelectedRow();
                if (i >= 0) {
                        tfMaPhieu.setText(jTablePhieuTra.getModel().getValueAt(i, 1).toString());
                        tfMaPhieuMuon.setText(jTablePhieuTra.getModel().getValueAt(i, 2).toString());
                        tfMaDG.setText(jTablePhieuTra.getModel().getValueAt(i, 3).toString());
                        tfMaSach.setText(jTablePhieuTra.getModel().getValueAt(i, 4).toString());
                        tfMaNhanVien.setText(jTablePhieuTra.getModel().getValueAt(i, 5).toString());
                        tfHanTra.setText(jTablePhieuTra.getModel().getValueAt(i, 6).toString());
                        tfNgayTra.setText(jTablePhieuTra.getModel().getValueAt(i, 7).toString());
                        tfSoLuong.setText(jTablePhieuTra.getModel().getValueAt(i, 8).toString());
                        tfTinhTrang.setText(jTablePhieuTra.getModel().getValueAt(i, 9).toString());
                        tfSoNgayQuaHan.setText(jTablePhieuTra.getModel().getValueAt(i, 10).toString());
                }
        }
        // GEN-LAST:event_jTablePhieuTraMouseClicked

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jButton2ActionPerformed

        private void tfMaDGActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfMaDGActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_tfMaDGActionPerformed

        private void tfMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfMaNhanVienActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_tfMaNhanVienActionPerformed

        private void tfHanTraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfHanTraActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_tfHanTraActionPerformed

        private void tfTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfTinhTrangActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_tfTinhTrangActionPerformed

        private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLoadActionPerformed
                // TODO add your handling code here:
                boolean flag = false;
                for (PhieuTra phieuTra : list) {
                        if (tfMaPhieuMuon.getText().equals(phieuTra.getMaPhieuMuon())) {
                                flag = true;

                        }
                }
                if (flag) {
                        JOptionPane.showMessageDialog(this, "Bạn đã trả sách");
                } else {
                        PhieuMuonBUS pmbus = new PhieuMuonBUS();
                        listusers = userBUS.getUsers();
                        User user = listusers.get(0);
                        tfMaNhanVien.setText(user.getMaUser());
                        for (PhieuMuon pm : pmbus.loadData()) {
                                System.out.println(pm.getMaPhieu());
                                if (tfMaPhieuMuon.getText().equals(pm.getMaPhieu())) {
                                        tfMaDG.setText(pm.getMaDocGia());
                                        tfMaSach.setText(pm.getMaSach());
                                        tfHanTra.setText(Menu.MenuHand.convert(pm.getNgayTra()));
                                        // tfHanTra.setText(pm.getNgayTra().toString());
                                        tfSoLuong.setText(String.valueOf(pm.getSoLuong()));
                                        tfNgayTra.setText(Menu.MenuHand.convert(LocalDate.now()));
                                        if (Menu.MenuHand.TruDate(pm.getNgayTra(), LocalDate.now()) > 0) {
                                                tfSoNgayQuaHan.setText(String.valueOf(Menu.MenuHand
                                                                .TruDate(pm.getNgayTra(), LocalDate.now())));
                                        } else {
                                                tfSoNgayQuaHan.setText("0");
                                        }

                                }
                        }
                        
                        tfMaPhieu.setText(Menu.MenuHand.FormatString(phieuTraBUS.getMaphieutra()));

                }

        }// GEN-LAST:event_btnLoadActionPerformed

        private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClearActionPerformed
                // TODO add your handling code here:
                //tfMaPhieu.setEditable(true);
                tfHanTra.setText("");
                tfMaPhieu.setText("");
                tfMaPhieuMuon.setText("");
                tfMaDG.setText("");
                tfMaNhanVien.setText("");
                tfNgayTra.setText("");
                tfSoLuong.setText("");
                tfSoNgayQuaHan.setText("");
                tfTinhTrang.setText("");
        }// GEN-LAST:event_btnClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnInExcel;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePhieuTra;
    private javax.swing.JTextField tfHanTra;
    private javax.swing.JTextField tfMaDG;
    private javax.swing.JTextField tfMaNhanVien;
    private javax.swing.JTextField tfMaPhieu;
    private javax.swing.JTextField tfMaPhieuMuon;
    private javax.swing.JTextField tfMaSach;
    private javax.swing.JTextField tfNgayTra;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfSoNgayQuaHan;
    private javax.swing.JTextField tfTinhTrang;
    // End of variables declaration//GEN-END:variables
}
