/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view.employee;

import com.mycompany.Object.TacGia.*;
import javax.swing.table.*;

import org.apache.commons.math3.stat.descriptive.summary.Product;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.DataFormat;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.util.ArrayList;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.time.LocalDate;

/**
 *
 * @author khang
 */
public class QuanLyTacGiaJPanel extends javax.swing.JPanel {
    TacGiaBUS tacGiaBUS = new TacGiaBUS();
    DefaultTableModel model;

    /**
     * Creates new form QuanLyTacGiaJPanel
     */
    public QuanLyTacGiaJPanel() {
        initComponents();
        model = (DefaultTableModel) tableTG.getModel();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupPhai = new javax.swing.ButtonGroup();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tfMa = new javax.swing.JTextField();
        tfTen = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jRadioButtonNam = new javax.swing.JRadioButton();
        jRadioButtonNu = new javax.swing.JRadioButton();
        tfNgaySinh = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnInExcel = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableTG = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        jPanel12.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridLayout());

        btnThem.setText("Thêm");
        btnThem.setMaximumSize(new java.awt.Dimension(72, 33));
        btnThem.setMinimumSize(new java.awt.Dimension(72, 33));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem);

        btnXoa.setText("Xoá");
        btnXoa.setMaximumSize(new java.awt.Dimension(99, 57));
        btnXoa.setMinimumSize(new java.awt.Dimension(72, 33));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa);

        btnSua.setText("Sửa");
        btnSua.setMaximumSize(new java.awt.Dimension(89, 55));
        btnSua.setMinimumSize(new java.awt.Dimension(72, 33));
        btnSua.setPreferredSize(new java.awt.Dimension(72, 33));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSua);

        btnLoad.setText("Load");
        btnLoad.setMaximumSize(new java.awt.Dimension(72, 33));
        btnLoad.setPreferredSize(new java.awt.Dimension(72, 33));
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        jPanel2.add(btnLoad);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel12.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        jLabel25.setText("Mã");
        jPanel3.add(jLabel25);

        jLabel26.setText("Tên");
        jPanel3.add(jLabel26);

        jLabel27.setText("Phái");
        jPanel3.add(jLabel27);

        jLabel28.setText("Ngày sinh");
        jPanel3.add(jLabel28);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel12.add(jPanel3, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        tfMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaActionPerformed(evt);
            }
        });
        jPanel4.add(tfMa);

        tfTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenActionPerformed(evt);
            }
        });
        jPanel4.add(tfTen);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        buttonGroupPhai.add(jRadioButtonNam);
        jRadioButtonNam.setText("Nam");
        jRadioButtonNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNamActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButtonNam);

        buttonGroupPhai.add(jRadioButtonNu);
        jRadioButtonNu.setText("Nữ");
        jPanel5.add(jRadioButtonNu);

        jPanel4.add(jPanel5);

        tfNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNgaySinhActionPerformed(evt);
            }
        });
        jPanel4.add(tfNgaySinh);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 186;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel12.add(jPanel4, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        btnInExcel.setText("In Excel");
        btnInExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInExcelActionPerformed(evt);
            }
        });
        jPanel1.add(btnInExcel);

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        jPanel1.add(btnTim);

        btnClear.setText("Clear");
        btnClear.setPreferredSize(new java.awt.Dimension(99, 57));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 91;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 63, 0, 0);
        jPanel12.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        add(jPanel12, gridBagConstraints);

        tableTG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Tên", "Phái", "Ngày sinh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTGMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tableTG);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 623;
        gridBagConstraints.ipady = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        add(jScrollPane6, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public void loadData() {
        ArrayList<TacGia> arr = new ArrayList<TacGia>();
        arr = tacGiaBUS.loadData();
        int i = 0;
        while (i <= arr.size() - 1) {
            TacGia tacGia = arr.get(i);
            model.addRow(new Object[] {
                    ++i, tacGia.getMaTacGia(), tacGia.getTenTacGia(), tacGia.getGioiTinh(), Menu.MenuHand.convert(tacGia.getNgaySinh())
            });
            tableTG.setModel(model);
        }
    }
    
    public void refreshData() {
        tacGiaBUS = new TacGiaBUS();
        loadData();
    }
    
    private void tfMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaActionPerformed

    private void tfTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenActionPerformed

    private void tfNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNgaySinhActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(getRootPane(),
                "Bạn có chắc muốn xoá " + tfTen.getText() + " không ?", "Chú ý",
                JOptionPane.YES_NO_OPTION);
        
        ArrayList<TacGia> arr = new ArrayList<TacGia>();
        arr = tacGiaBUS.loadData();

        if (reply == JOptionPane.YES_OPTION) {
            for (TacGia tacGia : arr) {
                if (tacGia.getMaTacGia().equals(tfMa.getText().trim())) {
                    JOptionPane.showMessageDialog(this, tacGiaBUS.delete(tacGia));                  
                    break;
                }
            }
        }
        model.setRowCount(0);
        refreshData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tfMa.setText("");
        tfTen.setText("");
        tfNgaySinh.setText("");
        buttonGroupPhai.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tableTGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTGMouseClicked
        // TODO add your handling code here:
        int i = tableTG.getSelectedRow();
        if (i >= 0) {
            
            tfMa.setText(tableTG.getModel().getValueAt(i, 1).toString());
            tfTen.setText(tableTG.getModel().getValueAt(i, 2).toString());
            if (tableTG.getModel().getValueAt(i, 3).toString().toUpperCase().equals("NAM")) {
                jRadioButtonNam.setSelected(true);
            } else {
                jRadioButtonNu.setSelected(true);
            }
            tfNgaySinh.setText(tableTG.getModel().getValueAt(i, 4).toString());
        }
    }//GEN-LAST:event_tableTGMouseClicked

    private void jRadioButtonNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNamActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            if (tfMa.getText().trim().equals("") || 
                tfTen.getText().trim().equals("")|| 
                tfNgaySinh.getText().trim().equals("")||
                jRadioButtonNam.isSelected() == false && jRadioButtonNu.isSelected() == false) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
                
            } else {
                TacGia tacGia = new TacGia();
                tacGia.setMaTacGia(tfMa.getText());
                tacGia.setTenTacGia(tfTen.getText());
                tacGia.setNgaySinh(LocalDate.parse(tfNgaySinh.getText()));
                if(jRadioButtonNam.isSelected())
                    tacGia.setGioiTinh("NAM");
                else tacGia.setGioiTinh("NỮ");
                tacGia.setTonTai(true);
   
                JOptionPane.showMessageDialog(this, tacGiaBUS.add(tacGia));
                model.setRowCount(0);
                refreshData();
            }
        } catch (Exception ex) {
            System.out.print(ex);
        }
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        try{
            ArrayList<TacGia> arr = new ArrayList<TacGia>();
            String maTacGia = tfMa.getText();
            String tenTacGia = tfTen.getText();
            String ngaySinh = tfNgaySinh.getText();
            String gioiTinh = "";
            if(jRadioButtonNam.isSelected())
                gioiTinh += "NAM";
            else gioiTinh += "NỮ";

            arr = tacGiaBUS.search(maTacGia, tenTacGia, gioiTinh, ngaySinh);
            if (arr.size() != 0) {
                JOptionPane.showMessageDialog(this, "Hoàn tất tìm kiếm!");
                model.setRowCount(0);
                int i = 0;
                while (i <= arr.size() - 1) {
                    TacGia tacGia = arr.get(i);
                    model.addRow(new Object[] {
                            ++i,tacGia.getMaTacGia(), tacGia.getTenTacGia(), tacGia.getGioiTinh(), tacGia.getNgaySinh()
                    });
                }
            } else JOptionPane.showMessageDialog(this, "Không có dữ liệu cần tìm!");
        } catch(Exception ex) {
            System.out.print(ex);
        } 
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        ArrayList<TacGia> arr = new ArrayList<TacGia>();
        arr = tacGiaBUS.loadData();
        for (TacGia tacGia : arr) {
            if (tacGia.getMaTacGia().equals(tfMa.getText().trim())) {
                tacGia.setTenTacGia(tfTen.getText());               
                if(jRadioButtonNam.isSelected())
                    tacGia.setGioiTinh("NAM");
                else tacGia.setGioiTinh("NỮ");
                tacGia.setNgaySinh(LocalDate.parse(tfNgaySinh.getText()));
                
                JOptionPane.showMessageDialog(this, tacGiaBUS.update(tacGia));
                break;
            }
        }
        model.setRowCount(0);
        refreshData();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnInExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInExcelActionPerformed
        // TODO add your handling code here:
        try{
            JFileChooser fChooser = new JFileChooser();
            int choose = fChooser.showSaveDialog(null);
            if(choose == JFileChooser.APPROVE_OPTION) {
                XSSFWorkbook workbook = new XSSFWorkbook();
                XSSFSheet sheet = workbook.createSheet("Tác giả");
                XSSFRow row = null;
                Cell cell = null;

                String dateFormat = "yyyy-MM-dd";
                CellStyle style = workbook.createCellStyle();
                DataFormat dataFormat = workbook.createDataFormat();
                style.setDataFormat(dataFormat.getFormat(dateFormat));

                row = sheet.createRow(3);

                cell = row.createCell(0, CellType.STRING);
                cell.setCellValue("STT");

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue("Mã tác giả");

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue("Tên tác giả");

                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue("Phái");

                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue("Ngày sinh");

                ArrayList<TacGia> arr = tacGiaBUS.loadData();

                for(int i = 0; i < arr.size(); i++) {
                    row = sheet.createRow(4 + i);

                    cell = row.createCell(0, CellType.NUMERIC);
                    cell.setCellValue(i + 1);

                    cell = row.createCell(1, CellType.STRING);
                    cell.setCellValue(arr.get(i).getMaTacGia());

                    cell = row.createCell(2, CellType.STRING);
                    cell.setCellValue(arr.get(i).getTenTacGia());

                    cell = row.createCell(3, CellType.STRING);
                    cell.setCellValue(arr.get(i).getGioiTinh());

                    cell = row.createCell(4);
                    cell.setCellValue(arr.get(i).getNgaySinh());
                    cell.setCellStyle(style);
                }

                File file = new File(fChooser.getSelectedFile().toString() + ".xlsx");
                try {
                    FileOutputStream fo = new FileOutputStream(file);
                    workbook.write(fo);
                    JOptionPane.showMessageDialog(this, "Đã in!");
                    fo.close();
                    workbook.close();
                } catch(FileNotFoundException e) {
                    System.out.println(e);
                }
            }
            
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnInExcelActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        refreshData();
    }//GEN-LAST:event_btnLoadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnInExcel;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroupPhai;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButtonNam;
    private javax.swing.JRadioButton jRadioButtonNu;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tableTG;
    private javax.swing.JTextField tfMa;
    private javax.swing.JTextField tfNgaySinh;
    private javax.swing.JTextField tfTen;
    // End of variables declaration//GEN-END:variables
}
