/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view.KH;

import java.util.ArrayList;

import com.mycompany.Object.USER.User;
import com.mycompany.Object.USER.UserBUS;

/**
 *
 * @author khang
 */
public class TrangChinhJPanel extends javax.swing.JPanel {

    UserBUS userBUS = new UserBUS();
    ArrayList<User> listusers = new ArrayList<User>();

    /**
     * Creates new form TrangChinhJPanel
     */
    public TrangChinhJPanel() {
        initComponents();
        LoadData();
    }

    public void LoadData() {
        listusers = userBUS.getUsers();
        User user = listusers.get(0);
        jLabelTenKH.setText("Chào mừng " + user.getTenUser() + " đã đăng nhập!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTenKH = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabelTenKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTenKH.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTenKH.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabelTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabelTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTenKH;
    // End of variables declaration//GEN-END:variables
}
